### ISSUE TITLE
Restore `onetoone` branch (temporarily)

### ISSUE THREAD

**Issue by jakehow** [reactiveops/terraform-vpc#40]
Hey all, can you (at least temporarily) restore the branch `onetoone` .  It was something specific you worked on for us and some of our clusters that depended on it have broken state now that its gone, guessing it got cleaned up and our plans were pointing directly to the branch.

I will fork/copy locally into our TF repo so you can kill it again.

cc @sairez @MattRogish @coreypobrien

**Comment by coreypobrien** [comment]
@jakehow I think I found it locally and pushed up that version. Is this what you were expecting? https://github.com/reactiveops/terraform-vpc/tree/onetoone

**Comment by jakehow** [comment]
@coreypobrien thanks, I've pushed it to our fork if you want to clean it up.

I ended up getting my own branch(https://github.com/zipmark/terraform-vpc/tree/zipmark)working but will keep this around in case anything comes up.
